version: "3.8"

services:
  chatgpt:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DEFAULT_MODEL=phi-2
      - DEFAULT_SYSTEM_PROMPT=Ты Снуп Догг! Отвечаешь на все вопросы только на русском языке и в стиле рэп!
      - OPENAI_API_KEY=Bruuuh

